### ISSUE TITLE
Repo Meta

### ISSUE THREAD

**Issue by gavindsouza** [frappe/payments#1]
- [x] Maintain history - see how https://github.com/frappe/healthcare and other apps do it
- [x] Name of the app - how about `payment_gateway`, `payments` or `gateways`? _(in order of preference)_ Having frappe in the title feels quite redundant

**Comment by phot0n** [comment]
>  Maintain history - see how https://github.com/frappe/healthcare and other apps do it

ah i thought i did that, seems i messed something now most commits show "x authored and phot0n committed" 😅 

> Name of the app - how about payment_gateway, payments or gateways? (in order of preference) Having frappe in the title feels quite redundant

payments seems better

**Comment by ankush** [comment]
- [x] check licensing. If you're moving any code from ERPNext to here it has to be licensed under GPL3. 
- [x] Update readme with installation info and link to docs
- [x] Add CI
- [x] Bulk format and enforce (history is likely all messed up anyway, this is a clean start)

**Comment by afalfallaj** [comment]
@ankush for any chance is it possible to have release tag? (instead relay on develop branch on install erpnext)
